### ISSUE TITLE
Could not load file or assembly 'StackExchange.Redis.StrongName, Version=1.2.1.0

### ISSUE THREAD

**Issue by guilhermelabigalini** [Azure/aspnet-redis-providers#69]
I'm using Microsoft.Web.RedisSessionStateProvider.2.2.4 and is dependent on StackExchange.Redis.StrongName - 1.1.608, this dependency is installed with nuget, But when I run my application its trying to use StackExchange.Redis.StrongName - 1.2.1.0.

Any suggestion?

```
Could not load file or assembly 'StackExchange.Redis.StrongName, Version=1.2.1.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.FileLoadException: Could not load file or assembly 'StackExchange.Redis.StrongName, Version=1.2.1.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by guilhermelabigalini** [comment]
I had to manually upgrade the StackExchange.Redis.StrongName from 1.1.608 to 1.2.1.0 to resolve the issue.

**Comment by JonCole** [comment]
Thanks for letting us know - this looks like a bug in our nuspec.  We will publish a new package with the fix shortly.

**Comment by SiddharthChatrolaMs** [comment]
This issue is fixed in https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/2.2.5 and https://www.nuget.org/packages/Microsoft.Web.RedisOutputCacheProvider/1.7.5

**Comment by spelltwister** [comment]
I am still getting this error in 2.2.5.

**Comment by SiddharthChatrolaMs** [comment]
I just tested session state (2.2.5) and output cache (1.7.5) with StackExchange.Redis.StrongName (1.2.1 and 1.2.3) in a small test app and couldn't reproduce the error. Are you doing some special case scenario? Can you please provide small reproducible test app?

**Comment by woric** [comment]
Can confirm that this issue still exists when using session state 2.2.5.342 and StackExchange.Redis.StrongName 1.2.3.*

I rolled back the project to use StackExchange.Redis.StrongName 1.2.1 and it worked again. 

* I don't think I am using the output cache assembly, at least not to my knowledge. There is certainly no assembly in my bin folder.

**Comment by woric** [comment]
Further investigation shows that 1.2.3 is not compatible with .NET 4.0 and above. (see https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes)

This means that anyone using .NET 4.0 must manually downgrade the StackExchange.Redis.StrongName package to 1.2.1, but people using earlier versions of .NET will be OK.

IMO, the session state nuget package should be tied to 1.2.1 until they sort out their problem.

**Comment by yashahhhax** [comment]
This issue is still exist.
can someone confirm how to upgrade from  StackExchange.Redis.StrongName 1.1.608 to 1.2.6
